"""修复评论模块bug

Revision ID: c2595d287b98
Revises: da1048fe4fc3
Create Date: 2019-11-12 16:48:55.698988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2595d287b98'
down_revision = 'da1048fe4fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_column('comments', 'disables')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disables', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
